// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SessionDaoBase.vsl in andromda-ejb3-cartridge.
//
package org.andromda.howto2.rental;

/**
 * <p>
 * Base EJB3 DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>org.andromda.howto2.rental.Person</code>.
 * </p>
 *
 * @see org.andromda.howto2.rental.PersonDao
 */
@javax.ejb.TransactionAttribute(javax.ejb.TransactionAttributeType.REQUIRED)
@javax.ejb.Local({org.andromda.howto2.rental.PersonDao.class})
public abstract class PersonDaoBase
    implements org.andromda.howto2.rental.PersonDao
{
    // ------ Session Context Injection ------
    
    @javax.annotation.Resource
    protected javax.ejb.SessionContext context;

    // ------ Persistence Context Injection --------

    /**
     * Inject persistence context howtomodelcaching     
     */
    @javax.persistence.PersistenceContext(unitName = "howtomodelcaching")    
    protected javax.persistence.EntityManager emanager;
    
    /**
     * @see org.andromda.howto2.rental.PersonDao#load(int,)
     */
    public Object load(final int transform, final java.lang.Long id)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Person.load - 'id' can not be null");
        }
        try
        {
            final Object entity = (org.andromda.howto2.rental.Person)emanager.find(org.andromda.howto2.rental.Person.class, id);
            return transformEntity(transform, (org.andromda.howto2.rental.Person)entity);
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#load()
     */
    public org.andromda.howto2.rental.Person load( final java.lang.Long id)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (org.andromda.howto2.rental.Person)this.load(TRANSFORM_NONE, id);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<org.andromda.howto2.rental.Person> loadAll()
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (java.util.Collection<org.andromda.howto2.rental.Person>)this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query query = emanager.createNamedQuery("Person.findAll");
            java.util.List<org.andromda.howto2.rental.Person> results = query.getResultList();
            this.transformEntities(transform, results);
            return results;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(org.andromda.howto2.rental.Person)
     */
    public org.andromda.howto2.rental.Person create(org.andromda.howto2.rental.Person person)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (org.andromda.howto2.rental.Person)this.create(TRANSFORM_NONE, person);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(int transform, org.andromda.howto2.rental.Person)
     */
    public Object create(final int transform, final org.andromda.howto2.rental.Person person)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (person == null)
        {
            throw new IllegalArgumentException(
                "Person.create - 'person' can not be null");
        }
        
        try
        {
            emanager.persist(person);
            emanager.flush();
            return this.transformEntity(transform, person);
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(java.util.Collection<org.andromda.howto2.rental.Person>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<org.andromda.howto2.rental.Person> create(final java.util.Collection<org.andromda.howto2.rental.Person> entities)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(int, java.util.Collection<org.andromda.howto2.rental.Person>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection create(final int transform, final java.util.Collection<org.andromda.howto2.rental.Person> entities)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Person.create - 'entities' can not be null");
        }
        java.util.Collection results = new java.util.ArrayList();
        try
        {
            for (final java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
            {
                results.add(create(transform, (org.andromda.howto2.rental.Person)entityIterator.next()));
            }
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
        return results;
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(java.lang.String, java.util.Date)
     */
    public org.andromda.howto2.rental.Person create(
        java.lang.String name,
        java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (org.andromda.howto2.rental.Person)this.create(TRANSFORM_NONE, name, birthDate);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#create(int, java.lang.String, java.util.Date)
     */
    public Object create(
        final int transform,
        java.lang.String name,
        java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        org.andromda.howto2.rental.Person entity = new org.andromda.howto2.rental.Person();
        entity.setName(name);
        entity.setBirthDate(birthDate);
        return this.create(transform, entity);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#update(org.andromda.howto2.rental.Person)
     */
    public void update(org.andromda.howto2.rental.Person person)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (person == null)
        {
            throw new IllegalArgumentException(
                "Person.update - 'person' can not be null");
        }
        try
        {
            emanager.merge(person);
            emanager.flush();
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#update(java.util.Collection<org.andromda.howto2.rental.Person>)
     */
    public void update(final java.util.Collection<org.andromda.howto2.rental.Person> entities)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Person.update - 'entities' can not be null");
        }
        try
        {
            for (final java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
            {
                update((org.andromda.howto2.rental.Person)entityIterator.next());
            }
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#remove(org.andromda.howto2.rental.Person)
     */
    public void remove(org.andromda.howto2.rental.Person person)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (person == null)
        {
            throw new IllegalArgumentException(
                "Person.remove - 'person' can not be null");
        }
        try
        {
            emanager.remove(person);
            emanager.flush();
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long id)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "Person.remove - 'id' can not be null");
        }
        try
        {
            final org.andromda.howto2.rental.Person entity = this.load(id);
            if (entity != null)
            {
                this.remove(entity);
            }
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#remove(java.util.Collection<org.andromda.howto2.rental.Person>)
     */
    public void remove(java.util.Collection<org.andromda.howto2.rental.Person> entities)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Person.remove - 'entities' can not be null");
        }
        try
        {
            for (final java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
            {
                remove((org.andromda.howto2.rental.Person)entityIterator.next());
            }
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findAll()
     */
    public java.util.List findAll()
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return this.findAll(TRANSFORM_NONE);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findAll(java.lang.String)
     */
    public java.util.List findAll(final java.lang.String queryString)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return this.findAll(TRANSFORM_NONE, queryString);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findAll(int)
     */
    public java.util.List findAll(final int transform)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createNamedQuery("Person.findAll");
            java.util.List results = queryObject.getResultList();
            transformEntities(transform, results);
            return results;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findAll(int, java.lang.String)
     */
    public java.util.List findAll(final int transform, final java.lang.String queryString)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createQuery(queryString);
            java.util.List results = queryObject.getResultList();
            transformEntities(transform, results);
            return results;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByName(java.lang.String)
     */
    public java.lang.String findByName(java.lang.String name)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (java.lang.String)this.findByName(TRANSFORM_NONE, name);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByName(java.lang.String, java.lang.String)
     */
    public java.lang.String findByName(final java.lang.String queryString, final java.lang.String name)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return (java.lang.String)this.findByName(TRANSFORM_NONE, queryString, name);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByName(int, java.lang.String)
     */
    public Object findByName(final int transform, final java.lang.String name)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createNamedQuery("Person.findByName");
            queryObject.setParameter("name", name);
            Object result = queryObject.getSingleResult();
            result = transformEntity(transform, (org.andromda.howto2.rental.Person)result);
            return result;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByName(int, java.lang.String, java.lang.String)
     */
    public Object findByName(final int transform, final java.lang.String queryString, final java.lang.String name)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createQuery(queryString);
            queryObject.setParameter("name", name);
            Object result = queryObject.getSingleResult();
            result = transformEntity(transform, (org.andromda.howto2.rental.Person)result);
            return result;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByNameOrBirthDate(java.lang.String, java.util.Date)
     */
    public java.util.Collection findByNameOrBirthDate(java.lang.String name, java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return this.findByNameOrBirthDate(TRANSFORM_NONE, name, birthDate);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByNameOrBirthDate(java.lang.String, java.lang.String, java.util.Date)
     */
    public java.util.Collection findByNameOrBirthDate(final java.lang.String queryString, final java.lang.String name, final java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        return this.findByNameOrBirthDate(TRANSFORM_NONE, queryString, name, birthDate);
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByNameOrBirthDate(int, java.lang.String, java.util.Date)
     */
    public java.util.Collection findByNameOrBirthDate(final int transform, final java.lang.String name, final java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createNamedQuery("Person.findByNameOrBirthDate");
            queryObject.setParameter("name", name);
            queryObject.setParameter("birthDate", birthDate, javax.persistence.TemporalType.DATE);
            java.util.List results = queryObject.getResultList();
            transformEntities(transform, results);
            return results;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * @see org.andromda.howto2.rental.PersonDao#findByNameOrBirthDate(int, java.lang.String, java.lang.String, java.util.Date)
     */
    public java.util.Collection findByNameOrBirthDate(final int transform, final java.lang.String queryString, final java.lang.String name, final java.util.Date birthDate)
        throws org.andromda.howto2.rental.PersonDaoException
    {
        try
        {
            javax.persistence.Query queryObject = emanager.createQuery(queryString);
            queryObject.setParameter("name", name);
            queryObject.setParameter("birthDate", birthDate, javax.persistence.TemporalType.DATE);
            java.util.List results = queryObject.getResultList();
            transformEntities(transform, results);
            return results;
        }
        catch (Exception ex)
        {
            throw new org.andromda.howto2.rental.PersonDaoException(ex);
        }
    }

    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>org.andromda.howto2.rental.PersonDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link org.andromda.howto2.rental.PersonDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected Object transformEntity(final int transform, final org.andromda.howto2.rental.Person entity)
    {
        Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,org.andromda.howto2.rental.Person)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>org.andromda.howto2.rental.PersonDao</code>
     * @param entities the collection of entities to transform
     * @return the same collection as the argument, but this time containing the transformed entities
     * @see #transformEntity(int,org.andromda.howto2.rental.Person)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}