// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

/**
 * TODO: Model Documentation for org.andromda.cartridges.angularjs.metafacades.AngularModelAttribute
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngularModelAttribute.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngularModelAttribute
 */
public class AngularModelAttributeLogicImpl
    extends AngularModelAttributeLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularModelAttributeLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngularModelAttribute
     */
    public AngularModelAttributeLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }


}