// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

/**
 * Represents the portlet preferences for a given use case (assuming the JSF application being
 * generated is a portlet).
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngularJSPortletPreferences.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngularJSPortletPreferences
 */
public class AngularJSPortletPreferencesLogicImpl
    extends AngularJSPortletPreferencesLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularJSPortletPreferencesLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSPortletPreferences
     */
    public AngularJSPortletPreferencesLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * Any portlet preferences associated to this use case.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSPortletPreferences#getUseCase()
     */
    protected Object handleGetUseCase()
    {
        // TODO add your implementation here!
        return null;
    }
}