// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

/**
 * Represents an operation for a JSF controller.
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation
 */
public class AngularJSControllerOperationLogicImpl
    extends AngularJSControllerOperationLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularJSControllerOperationLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation
     */
    public AngularJSControllerOperationLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * The fully qualified path of the form file.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getFullyQualifiedFormPath()
     */
    protected String handleGetFullyQualifiedFormPath()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The fully qualified form name.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getFullyQualifiedFormName()
     */
    protected String handleGetFullyQualifiedFormName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The form name the corresponds to this controller operation.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getFormName()
     */
    protected String handleGetFormName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The operation call that takes the appropriate form as an argument.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getFormCall()
     */
    protected String handleGetFormCall()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The controller operation signature that takes the appropriate form (if this operation has at
     * least one form field) as an argument.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getFormSignature()
     */
    protected String handleGetFormSignature()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The controller implementation operation signature that takes the appropriate form (if this
     * operation has at least one form field) as an argument.
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSControllerOperation#getImplementationFormSignature()
     */
    protected String handleGetImplementationFormSignature()
    {
        // TODO put your implementation here.
        return null;
    }
}