// license-header java merge-point
//
// Generated by: SessionBeanImpl.vsl in andromda-ejb3-cartridge.
//
package org.andromda.demo.ejb3.book;

/**
 * @see org.andromda.demo.ejb3.book.BookManagerBean
 */
/**
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, define the session bean in the ejb-jar.xml descriptor
 * @javax.ejb.Stateless
 */
/**
 * Uncomment to enable webservices for BookManagerBean
 *@javax.jws.WebService(endpointInterface = "org.andromda.demo.ejb3.book.BookManagerWSInterface")
 */
public class BookManagerBean 
    extends org.andromda.demo.ejb3.book.BookManagerBase 
{
    // --------------- Constructors ---------------
    
    public BookManagerBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------
    
    /**
     * @see org.andromda.demo.ejb3.book.BookManagerBase#getAllBooks()
     */
    protected java.util.Collection handleGetAllBooks()
        throws java.lang.Exception
    {
        return getBookDao().loadAll();
    }


    // -------- Lifecycle Callback Impl --------------
    
}
