// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.hibernate.metafacades;

import org.andromda.metafacades.uml.ParameterFacade;

/**
 * TODO: Model Documentation for
 * org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation
 * MetafacadeLogic implementation for org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation.
 *
 * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation
 */
public class HibernateQueryOperationLogicImpl
    extends HibernateQueryOperationLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for HibernateQueryOperationLogicImpl
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation
     */
    public HibernateQueryOperationLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * Indicates whether or not the query parameters used for the body of the finder should be named
     * ':someParam' or unnamed '?'.
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation#isUseNamedParameters()
     */
    protected boolean handleIsUseNamedParameters()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * The actual query returned for the body of the finder.
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation#getQuery()
     */
    protected String handleGetQuery()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Returns <code>true</code> if the operation is a criteria finder.
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation#isCriteriaFinder()
     */
    protected boolean handleIsCriteriaFinder()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * Returns the argument that will contain the criteria search parameters.
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation#getCriteriaArgument()
     */
    protected ParameterFacade handleGetCriteriaArgument()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Gets the query; taking the entity of which should be included in the query (not counting
     * queries that are explicitly modeled in OCL).
     * @see org.andromda.cartridges.hibernate.metafacades.HibernateQueryOperation#getQuery(HibernateEntity)
     */
    protected String handleGetQuery(HibernateEntity entity)
    {
        // TODO put your implementation here.
        return null;
    }
}