// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * Generated by DaoImpl.vsl in andromda-ejb3-cartridge on 08/06/2014 10:56:24.
 * You can (and have to!) safely modify it by hand.
 */
package org.andromda.demo.ejb3.rental;

/**
 * @see org.andromda.demo.ejb3.rental.RentalCar
 */
public class RentalCarDaoImpl
    extends RentalCarDaoBase
{
    // This entity has no Business Operations and no ValueObject dependency references
    /**
     * @see org.andromda.demo.ejb3.rental.RentalCarDao#allCarsAreRented()
     */
    @Override
    protected boolean handleAllCarsAreRented()
    {
        // TODO implement public boolean handleAllCarsAreRented()
        return false;
    }
}
