// license-header java merge-point
//
// Generated by: SessionBeanImpl.vsl in andromda-ejb3-cartridge.
//
package org.andromda.demo.ejb3.employee;

/**
 * @see org.andromda.demo.ejb3.employee.EmployeeServiceBean
 */
/**
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, define the session bean in the ejb-jar.xml descriptor
 * @javax.ejb.Stateless
 */
/**
 * Uncomment to enable webservices for EmployeeServiceBean
 *@javax.jws.WebService(endpointInterface = "org.andromda.demo.ejb3.employee.EmployeeServiceWSInterface")
 */
public class EmployeeServiceBean 
    extends org.andromda.demo.ejb3.employee.EmployeeServiceBase 
{
    // --------------- Constructors ---------------
    
    public EmployeeServiceBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------
    
    /**
     * @see org.andromda.demo.ejb3.employee.EmployeeServiceBase#addEmployee(org.andromda.demo.ejb3.employee.Employee)
     */
    protected int handleAddEmployee(org.andromda.demo.ejb3.employee.Employee employee)
        throws java.lang.Exception
    {
        return getEmployeeDao().create(employee).getId();
    }

    /**
     * @see org.andromda.demo.ejb3.employee.EmployeeServiceBase#getEmployee(int)
     */
    protected org.andromda.demo.ejb3.employee.Employee handleGetEmployee(int id)
        throws java.lang.Exception
    {
        return getEmployeeDao().load(id);
    }

    /**
     * @see org.andromda.demo.ejb3.employee.EmployeeServiceBase#getAllEmployees()
     */
    protected java.util.Collection handleGetAllEmployees()
        throws java.lang.Exception
    {
        return getEmployeeDao().loadAll();
    }

    /**
     * @see org.andromda.demo.ejb3.employee.EmployeeServiceBase#getEmployeesByContract(org.andromda.demo.ejb3.employee.EmployeeContractType)
     */
    protected java.util.Collection handleGetEmployeesByContract(org.andromda.demo.ejb3.employee.EmployeeContractType contractType)
        throws java.lang.Exception
    {
        return getEmployeeDao().findByContractType(contractType);
    }


    // -------- Lifecycle Callback Impl --------------
    
}
