package org.andromda.samples.carrental.inventory;

import javax.ejb.EntityContext;
import javax.ejb.RemoveException;
//import org.apache.log4j.Logger;

/**
 * The Car entity bean.
 *
 * <p>
 *  Represents a car. @author Matthias Bohlen
 * </p>
 *
 * <p>This class is intended to hold manual changes to the autogenerated
 * implementation in {@link CarBean}.</p>
 */
public abstract class CarBeanImpl extends CarBean {
    //private static Logger log = Logger.getLogger(CarBeanImpl.class);
	private EntityContext ctx;
	
	public void setEntityContext(EntityContext ctx) {
        //if(log.isDebugEnabled()) log.debug("CarBean.setEntityContext...");
        this.ctx = ctx;
    }

    public void unsetEntityContext() {
        //if(log.isDebugEnabled()) log.debug("CarBean.unsetEntityContext...");
        ctx = null;
    }

    public void ejbRemove() throws RemoveException {
        //if(log.isDebugEnabled()) log.debug("CarBean.ejbRemove...");
    }

    public void ejbLoad() {
        //if(log.isDebugEnabled()) log.debug("CarBean.ejbLoad...");
    }

    public void ejbStore() {
        //if(log.isDebugEnabled()) log.debug("CarBean.ejbStore...");
    }

    public void ejbPassivate() {
        //if(log.isDebugEnabled()) log.debug("CarBean.ejbPassivate...");
    }

    public void ejbActivate() {
        //if(log.isDebugEnabled()) log.debug("CarBean.ejbActivate...");
    }

    /**
     * 
     */
    public org.andromda.samples.carrental.inventory.Car create(java.lang.Long id, java.lang.String registrationNumber, java.lang.String inventoryNumber) {
        // TODO put your implementation here.
        Car result = null;
        return result;
    }

}
