package org.andromda.core.simpleoo;

import org.andromda.core.xml.Association;
import org.andromda.core.xml.Pakkage;
import org.andromda.core.xml.Type;


/**
 * <p>Interface that allows for the interchangeable use of SimpleOO
 * objects and their corresponding IDs.  One can hand to each defined
 * method either a SimpleOO object or a string with the ID of one and
 * will always get back a SimpleOO object.</p>
 *
 * <p>This interface exists to overcome a bug in the current JAXB EA1
 * release.  The JAXB specification (version 0.21) states that an XML
 * attribute defined as IDREFS in a DTD will be presented in the
 * class generated by JAXB as a list or array of the referenced
 * elements.  Sadly, EA1 just returns a list of strings with the
 * IDs.</p>
 * 
 * @author Stefan Kuehnel
 *
 * @see <a href="http://developer.java.sun.com/developer/bugParade/bugs/4508672.html">JAXB Bug #4508672</a>
 * @see <a href="http://developer.java.sun.com/developer/bugParade/bugs/4532677.html">JAXB Bug #4532677</a>
 */
public interface Object2SimpleOOConverter
{

    /**
     * <p>Casts the given object into a Type.</p>
     *
     * @param o an <code>Object</code> that is either an instance of
     *          <code>Type</code> or a <code>String</code> with the id
     *          of a type
     * @return the casted <code>Type</code> value or null
     */
    Type convertToType(Object o);

    /**
     * <p>Casts the given object into a Pakkage.</p>
     *
     * @param o an <code>Object</code> that is either an instance of
     *          <code>Pakkage</code> or a <code>String</code> with the
     *          id of a package
     * @return the casted <code>Pakkage</code> value or null
     */
    Pakkage convertToPackage(Object o);


    /**
     * <p>Casts the given object into an Association.</p>
     *
     * @param o an <code>Object</code> that is either an instance of
     *          <code>Association</code> or a <code>String</code> with
     *          the id of an association
     * @return the casted <code>Association</code> value or null
     */
    Association convertToAssociation(Object o);

}
