// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  FleetModel::backend::bw.co.bitri.fleet::SortOrder
 * STEREOTYPE:   Enumeration
 */
export enum SortOrder {
    /** TODO: Model Documentation for Enumeration Literal DESC value "DESC" */
    DESC = "DESC",
    /** TODO: Model Documentation for Enumeration Literal ASC value "ASC" */
    ASC = "ASC"
}
