// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 02/19/2011 19:34:58-0200
package org.andromda.timetracker.web.timetrackerhome;

/**
 * @see org.andromda.timetracker.web.timetrackerhome.HomeController
 */
public class HomeControllerImpl
    extends HomeController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 979300859059208583L;

}