package org.andromda.samples.carrental.customers;

import javax.ejb.EntityContext;
import javax.ejb.RemoveException;
//import org.apache.log4j.Logger;

/**
 * The Customer entity bean.
 *
 * <p>
 *  Represents a customer in the car rental system. @author
 *  Matthias Bohlen
 * </p>
 *
 * <p>This class is intended to hold manual changes to the autogenerated
 * implementation in {@link CustomerBean}.</p>
 */
public abstract class CustomerBeanImpl extends CustomerBean {
    //private static Logger log = Logger.getLogger(CustomerBeanImpl.class);
	private EntityContext ctx;
	
	public void setEntityContext(EntityContext ctx) {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.setEntityContext...");
        this.ctx = ctx;
    }

    public void unsetEntityContext() {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.unsetEntityContext...");
        ctx = null;
    }

    public void ejbRemove() throws RemoveException {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.ejbRemove...");
    }

    public void ejbLoad() {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.ejbLoad...");
    }

    public void ejbStore() {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.ejbStore...");
    }

    public void ejbPassivate() {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.ejbPassivate...");
    }

    public void ejbActivate() {
        //if(log.isDebugEnabled()) log.debug("CustomerBean.ejbActivate...");
    }

    /**
     * 
     */
    public void addDriver(org.andromda.samples.carrental.customers.Driver driver)
        throws org.andromda.samples.carrental.customers.CustomerException {
        // TODO put your implementation here.
    }

    /**
     * 
     */
    public org.andromda.samples.carrental.customers.Customer create(long id, java.lang.String name, java.lang.String customerNo, java.lang.String password)
        throws org.andromda.samples.carrental.customers.CustomerException {
        // TODO put your implementation here.
        Customer result = null;
        return result;
    }

}
