// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.metafacades.emf.uml22;

import org.eclipse.uml2.uml.RedefinableTemplateSignature;

/**
 * 
 * MetafacadeLogic implementation for org.andromda.metafacades.uml.RedefinableTemplateSignatureFacade.
 *
 * @see org.andromda.metafacades.uml.RedefinableTemplateSignatureFacade
 */
public class RedefinableTemplateSignatureFacadeLogicImpl
    extends RedefinableTemplateSignatureFacadeLogic
{
    private static final long serialVersionUID = 4724256461948508278L;

    /**
     * Public constructor for RedefinableTemplateSignatureFacadeLogicImpl
     * @param metaObject 
     * @param context 
     * @see org.andromda.metafacades.uml.RedefinableTemplateSignatureFacade
     */
    public RedefinableTemplateSignatureFacadeLogicImpl (RedefinableTemplateSignature metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * 
     * @return shieldedElement(metaObject.getClassifier())
     * @see org.andromda.metafacades.uml.RedefinableTemplateSignatureFacade#getClassifier()
     */
    protected Object handleGetClassifier()
    {
        return shieldedElement(metaObject.getClassifier());
    }
}