package org.andromda.samples.carrental.contracts;

import javax.ejb.EntityContext;
import javax.ejb.RemoveException;
//import org.apache.log4j.Logger;

/**
 * The AccidentDoc entity bean.
 *
 * <p>
 *  Document that describes a car accident that has happened.
 *  @author Matthias Bohlen
 * </p>
 *
 * <p>This class is intended to hold manual changes to the autogenerated
 * implementation in {@link AccidentDocBean}.</p>
 */
public abstract class AccidentDocBeanImpl extends AccidentDocBean {
    //private static Logger log = Logger.getLogger(AccidentDocBeanImpl.class);
	private EntityContext ctx;
	
	public void setEntityContext(EntityContext ctx) {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.setEntityContext...");
        this.ctx = ctx;
    }

    public void unsetEntityContext() {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.unsetEntityContext...");
        ctx = null;
    }

    public void ejbRemove() throws RemoveException {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.ejbRemove...");
    }

    public void ejbLoad() {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.ejbLoad...");
    }

    public void ejbStore() {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.ejbStore...");
    }

    public void ejbPassivate() {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.ejbPassivate...");
    }

    public void ejbActivate() {
        //if(log.isDebugEnabled()) log.debug("AccidentDocBean.ejbActivate...");
    }

}
