package org.andromda.samples.carrental.customers;

import javax.ejb.EntityContext;
import javax.ejb.RemoveException;
//import org.apache.log4j.Logger;

/**
 * The Driver entity bean.
 *
 * <p>
 *  Represents a driver who is an employee of the customer's
 *  company. @author Matthias Bohlen
 * </p>
 *
 * <p>This class is intended to hold manual changes to the autogenerated
 * implementation in {@link DriverBean}.</p>
 */
public abstract class DriverBeanImpl extends DriverBean {
    //private static Logger log = Logger.getLogger(DriverBeanImpl.class);
	private EntityContext ctx;
	
	public void setEntityContext(EntityContext ctx) {
        //if(log.isDebugEnabled()) log.debug("DriverBean.setEntityContext...");
        this.ctx = ctx;
    }

    public void unsetEntityContext() {
        //if(log.isDebugEnabled()) log.debug("DriverBean.unsetEntityContext...");
        ctx = null;
    }

    public void ejbRemove() throws RemoveException {
        //if(log.isDebugEnabled()) log.debug("DriverBean.ejbRemove...");
    }

    public void ejbLoad() {
        //if(log.isDebugEnabled()) log.debug("DriverBean.ejbLoad...");
    }

    public void ejbStore() {
        //if(log.isDebugEnabled()) log.debug("DriverBean.ejbStore...");
    }

    public void ejbPassivate() {
        //if(log.isDebugEnabled()) log.debug("DriverBean.ejbPassivate...");
    }

    public void ejbActivate() {
        //if(log.isDebugEnabled()) log.debug("DriverBean.ejbActivate...");
    }

}
