
    alter table TIMECARD 
        drop constraint TIMECARD_SUBMITTERC;

    alter table TIMECARD 
        drop constraint TIMECARD_APPROVERC;

    alter table TIME_ALLOCATION 
        drop constraint TIME_ALLOCATION_TASKC;

    alter table TIME_ALLOCATION 
        drop constraint TIME_ALLOCATION_TIMECARDC;

    alter table USER_ROLE 
        drop constraint USER_ROLE_USERC;

    drop table TASK if exists;

    drop table TIMECARD if exists;

    drop table TIME_ALLOCATION if exists;

    drop table USERS if exists;

    drop table USER_ROLE if exists;

    create table TASK (
        ID BIGINT generated by default as identity,
        NAME VARCHAR(256) not null unique,
        primary key (ID)
    );

    create table TIMECARD (
        ID BIGINT generated by default as identity,
        STATUS VARCHAR(256) not null,
        START_DATE DATETIME not null,
        COMMENTS VARCHAR(256) not null,
        SUBMITTER BIGINT not null,
        APPROVER BIGINT,
        primary key (ID)
    );

    create table TIME_ALLOCATION (
        ID BIGINT generated by default as identity,
        TIME_PERIOD_START_TIME DATETIME not null,
        TIME_PERIOD_END_TIME DATETIME not null,
        TIMECARD BIGINT not null,
        TASK BIGINT not null,
        primary key (ID)
    );

    create table USERS (
        ID BIGINT generated by default as identity,
        USERNAME VARCHAR(256) not null unique,
        PASSWORD VARCHAR(256) not null,
        FIRST_NAME VARCHAR(256) not null,
        LAST_NAME VARCHAR(256) not null,
        EMAIL VARCHAR(256) not null unique,
        IS_ACTIVE BIT not null,
        CREATION_DATE DATETIME not null,
        COMMENT VARCHAR(256),
        primary key (ID)
    );

    create table USER_ROLE (
        ID BIGINT generated by default as identity,
        ROLE VARCHAR(256) not null,
        USER BIGINT,
        primary key (ID)
    );

    alter table TIMECARD 
        add constraint TIMECARD_SUBMITTERC 
        foreign key (SUBMITTER) 
        references USERS;

    alter table TIMECARD 
        add constraint TIMECARD_APPROVERC 
        foreign key (APPROVER) 
        references USERS;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TASKC 
        foreign key (TASK) 
        references TASK;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TIMECARDC 
        foreign key (TIMECARD) 
        references TIMECARD;

    alter table USER_ROLE 
        add constraint USER_ROLE_USERC 
        foreign key (USER) 
        references USERS;
