
    alter table TIMECARD 
        drop constraint TIMECARD_SUBMITTER_FKC;

    alter table TIMECARD 
        drop constraint TIMECARD_APPROVER_FKC;

    alter table TIME_ALLOCATION 
        drop constraint TIME_ALLOCATION_TIMECARD_FKC;

    alter table TIME_ALLOCATION 
        drop constraint TIME_ALLOCATION_TASK_FKC;

    alter table USER_ROLE 
        drop constraint USER_ROLE_USER_FKC;

    drop table TASK if exists;

    drop table TIMECARD if exists;

    drop table TIME_ALLOCATION if exists;

    drop table USERS if exists;

    drop table USER_ROLE if exists;

    create table TASK (
        ID BIGINT generated by default as identity,
        NAME VARCHAR(256) not null unique,
        primary key (ID)
    );

    create table TIMECARD (
        ID BIGINT generated by default as identity,
        STATUS VARCHAR(256) not null,
        START_DATE DATETIME not null,
        COMMENTS VARCHAR(256) not null,
        SUBMITTER_FK BIGINT not null,
        APPROVER_FK BIGINT,
        primary key (ID)
    );

    create table TIME_ALLOCATION (
        ID BIGINT generated by default as identity,
        TIME_PERIOD_START_TIME DATETIME not null,
        TIME_PERIOD_END_TIME DATETIME not null,
        TIMECARD_FK BIGINT not null,
        TASK_FK BIGINT not null,
        primary key (ID)
    );

    create table USERS (
        ID BIGINT generated by default as identity,
        USERNAME VARCHAR(256) not null unique,
        PASSWORD VARCHAR(256) not null,
        FIRST_NAME VARCHAR(256) not null,
        LAST_NAME VARCHAR(256) not null,
        EMAIL VARCHAR(256) not null unique,
        IS_ACTIVE BIT not null,
        CREATION_DATE DATETIME not null,
        COMMENT VARCHAR(256),
        primary key (ID)
    );

    create table USER_ROLE (
        ID BIGINT generated by default as identity,
        ROLE VARCHAR(256) not null,
        USER_FK BIGINT,
        primary key (ID)
    );

    alter table TIMECARD 
        add constraint TIMECARD_SUBMITTER_FKC 
        foreign key (SUBMITTER_FK) 
        references USERS;

    alter table TIMECARD 
        add constraint TIMECARD_APPROVER_FKC 
        foreign key (APPROVER_FK) 
        references USERS;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TIMECARD_FKC 
        foreign key (TIMECARD_FK) 
        references TIMECARD;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TASK_FKC 
        foreign key (TASK_FK) 
        references TASK;

    alter table USER_ROLE 
        add constraint USER_ROLE_USER_FKC 
        foreign key (USER_FK) 
        references USERS;
