// license-header java merge-point
//
// Generated by: SessionBeanImpl.vsl in andromda-ejb3-cartridge.
//
package org.andromda.demo.ejb3.customer;

import java.util.Collection;

/**
 * @see org.andromda.demo.ejb3.customer.CustomerServiceBean
 */
/**
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, define the session bean in the ejb-jar.xml descriptor
 * @javax.ejb.Stateless
 */
@javax.jws.WebService(endpointInterface = "org.andromda.demo.ejb3.customer.CustomerServiceWSInterface")
public class CustomerServiceBean 
    extends org.andromda.demo.ejb3.customer.CustomerServiceBase 
{
    // --------------- Constructors ---------------
    
    public CustomerServiceBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------
    
    /**
     * @see org.andromda.demo.ejb3.customer.CustomerServiceBase#addCustomer(org.andromda.demo.ejb3.customer.Customer)
     */
    protected void handleAddCustomer(org.andromda.demo.ejb3.customer.Customer customer)
        throws java.lang.Exception
    {
        getCustomerDao().create(customer);
    }

    /**
     * @see org.andromda.demo.ejb3.customer.CustomerServiceBase#getAllCustomers()
     */
    protected org.andromda.demo.ejb3.customer.Customer[] handleGetAllCustomers()
        throws java.lang.Exception
    {
        Collection customers = getCustomerDao().loadAll();
        return (org.andromda.demo.ejb3.customer.Customer[])customers.toArray(new Customer[customers.size()]);
    }


    // -------- Lifecycle Callback Impl --------------
    
}
