// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.metafacades.uml14;

/**
 * Represents an attribute of a WSDL type.
 * MetafacadeLogic implementation for org.andromda.metafacades.uml.WSDLTypeAttributeFacade.
 *
 * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade
 */
public class WSDLTypeAttributeFacadeLogicImpl
    extends WSDLTypeAttributeFacadeLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for WSDLTypeAttributeFacadeLogicImpl
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade
     */
    public WSDLTypeAttributeFacadeLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * Whether or not this WSDL Type attribute is nillable.
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade#isNillable()
     */
    protected boolean handleIsNillable()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * Is the attribute an XML attribute?
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade#isAttribute()
     */
    protected boolean handleIsAttribute()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * Is the attribute an XML element?
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade#isElement()
     */
    protected boolean handleIsElement()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * Class referenced by @XmlAdapter Jaxb annotation
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade#getXmlAdapter()
     */
    protected String handleGetXmlAdapter()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * XMLSchema type for Jaxb type mapping. Overrides default.
     * @see org.andromda.metafacades.uml.WSDLTypeAttributeFacade#getXmlSchemaType()
     */
    protected String handleGetXmlSchemaType()
    {
        // TODO put your implementation here.
        return null;
    }
}