// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 02/19/2011 19:35:00-0200
package org.andromda.timetracker.domain.crud;

import java.io.Serializable;

/**
 * @see org.andromda.timetracker.domain.crud.TaskController
 */
public class TaskControllerImpl
    extends TaskController
    implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1885600900854032821L;


}