// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

/**
 * TODO: Model Documentation for org.andromda.cartridges.angular.metafacades.AngularExceptionHandler
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularExceptionHandler.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler
 */
public class AngularExceptionHandlerLogicImpl
    extends AngularExceptionHandlerLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularExceptionHandlerLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler
     */
    public AngularExceptionHandlerLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * The key to use with this handler's message resource bundle that will retrieve the error
     * message template for this exception.
     * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler#getExceptionKey()
     */
    protected String handleGetExceptionKey()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The module-relative URI to the resource that will complete the request/response if this
     * exception occurs.
     * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler#getExceptionPath()
     */
    protected String handleGetExceptionPath()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Fully qualified Java class name of the exception type to register with this handler.
     * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler#getExceptionType()
     */
    protected String handleGetExceptionType()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularExceptionHandler.messageKey
     * @see org.andromda.cartridges.angular.metafacades.AngularExceptionHandler#getMessageKey()
     */
    protected String handleGetMessageKey()
    {
        // TODO put your implementation here.
        return null;
    }
}