// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angularjs.metafacades;

import java.util.Collection;

/**
 * TODO: Model Documentation for org.andromda.cartridges.angularjs.metafacades.AngularJSModel
 * MetafacadeLogic implementation for org.andromda.cartridges.angularjs.metafacades.AngularJSModel.
 *
 * @see org.andromda.cartridges.angularjs.metafacades.AngularJSModel
 */
public class AngularJSModelLogicImpl
    extends AngularJSModelLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularJSModelLogicImpl
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSModel
     */
    public AngularJSModelLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * TODO: Model Documentation for org.andromda.cartridges.angularjs.metafacades.AngularJSModel
     * @see org.andromda.cartridges.angularjs.metafacades.AngularJSModel#getAttribues()
     */
    protected Collection<AngularJSAttribute> handleGetAttribues()
    {
        // TODO add your implementation here!
        return null;
    }
}