// license-header java merge-point
//
// Generated by: SessionBeanImpl.vsl in andromda-ejb3-cartridge.
//
package org.andromda.demo.ejb3.ticket;

/**
 * @see org.andromda.demo.ejb3.ticket.TicketManagerBean
 */
/**
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, define the session bean in the ejb-jar.xml descriptor
 * @javax.ejb.Stateless
 */
/**
 * Uncomment to enable webservices for TicketManagerBean
 *@javax.jws.WebService(endpointInterface = "org.andromda.demo.ejb3.ticket.TicketManagerWSInterface")
 */
public class TicketManagerBean 
    extends org.andromda.demo.ejb3.ticket.TicketManagerBase 
{
    // --------------- Constructors ---------------
    
    public TicketManagerBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------
    
    /**
     * @see org.andromda.demo.ejb3.ticket.TicketManagerBase#addEmailTicket(org.andromda.demo.ejb3.ticket.EmailTicket)
     */
    protected void handleAddEmailTicket(org.andromda.demo.ejb3.ticket.EmailTicket ticket)
        throws java.lang.Exception
    {
        getEmailTicketDao().create(ticket);
    }

    /**
     * @see org.andromda.demo.ejb3.ticket.TicketManagerBase#addPaperTicket(org.andromda.demo.ejb3.ticket.PaperTicket)
     */
    protected void handleAddPaperTicket(org.andromda.demo.ejb3.ticket.PaperTicket ticket)
        throws java.lang.Exception
    {
        getPaperTicketDao().create(ticket);
    }


    // -------- Lifecycle Callback Impl --------------
    
}
