// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.metafacades.emf.uml22;
import java.util.ArrayList;
import java.util.List;
import org.andromda.metafacades.uml.ClassifierFacade;
import org.andromda.metafacades.uml.ModelElementFacade;
import org.andromda.metafacades.uml.OperationFacade;
import org.andromda.metafacades.uml.TypeMappings;
import org.andromda.metafacades.uml.UMLMetafacadeProperties;
import org.andromda.metafacades.uml.UMLProfile;
import org.andromda.metafacades.uml.WebServiceOperationFacade;
import org.andromda.metafacades.uml.webservice.WebServiceMetafacadeGlobals;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
/**
 * Represents an web service WSDL type.
 * MetafacadeLogic implementation for org.andromda.metafacades.uml.WSDLTypeFacade.
 *
 * @see org.andromda.metafacades.uml.WSDLTypeFacade
 */
public class WSDLTypeFacadeLogicImpl
    extends WSDLTypeFacadeLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for WSDLTypeFacadeLogicImpl
     * @see org.andromda.metafacades.uml.WSDLTypeFacade
     */
    public WSDLTypeFacadeLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }
    /**
     * The logger instance.
     */
    private static final Logger logger = Logger.getLogger(WSDLTypeFacadeLogicImpl.class);

    /**
     * @return String this.getSchemaType(true, true)
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getSchemaType()
     */
    public String handleGetSchemaType()
    {
        return this.getSchemaType(true, true);
    }

    /**
     * @param withPrefix
     * @param preserveArray
     * @return String WebServiceMetafacadeUtils.getSchemaType
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getSchemaType(boolean, boolean)
     */
    public String handleGetSchemaType(boolean withPrefix, boolean preserveArray)
    {
        return WebServiceMetafacadeUtils.getSchemaType(this, this.getSchemaTypeMappings(), this.getNamespacePrefix(),
                this.getName(), this.getWsdlArrayNamePrefix(), withPrefix, preserveArray);
    }

    /**
     * @return getName().insert(0, this.getWsdlArrayNamePrefix())
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getWsdlArrayName()
     */
    protected String handleGetWsdlArrayName()
    {
        StringBuilder name = new StringBuilder(StringUtils.trimToEmpty(this.getName()).replaceAll("\\[\\]", ""));
        name.insert(0, this.getWsdlArrayNamePrefix());
        return name.toString();
    }

    /**
     * @return String getConfiguredProperty(WebServiceMetafacadeGlobals.ARRAY_NAME_PREFIX)
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getWsdlArrayNamePrefix()
     */
    protected String handleGetWsdlArrayNamePrefix()
    {
        return String.valueOf(this.getConfiguredProperty(WebServiceMetafacadeGlobals.ARRAY_NAME_PREFIX));
    }

    /**
     * @return String this.getQualfiedNameLocalPartPattern().replaceAll("\\{0\\}")
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getQName()
     */
    protected String handleGetQName()
    {
        return this.getQualfiedNameLocalPartPattern().replaceAll("\\{0\\}", StringUtils.trimToEmpty(this.getName()));
    }

    /**
     * @return String WebServiceMetafacadeUtils.reversePackage(packageName)
     * @see org.andromda.cartridges.webservice.metafacades.WSDLType#getNamespace()
     */
    protected String handleGetNamespace()
    {
        String packageName = this.getPackageName();
        if (this.isReverseNamespace())
        {
            packageName = WebServiceMetafacadeUtils.reversePackage(packageName);
        }
        return this.getNamespacePattern().replaceAll("\\{0\\}", StringUtils.trimToEmpty(packageName));
    }

    /**
     * Gets the array suffix from the configured metafacade properties.
     *
     * @return the array suffix.
     */
    public String getArraySuffix()
    {
        return String.valueOf(this.getConfiguredProperty(UMLMetafacadeProperties.ARRAY_NAME_SUFFIX));
    }

    /**
     * Gets the schemaType mappings that have been set for this schema type.
     *
     * @return the TypeMappings instance.
     */
    private TypeMappings getSchemaTypeMappings()
    {
        final String propertyName = WebServiceMetafacadeGlobals.SCHEMA_TYPE_MAPPINGS_URI;
        Object property = this.getConfiguredProperty(propertyName);
        TypeMappings mappings = null;
        String uri = null;
        if (property instanceof String)
        {
            uri = (String)property;
            try
            {
                mappings = TypeMappings.getInstance(uri);
                mappings.setArraySuffix(this.getArraySuffix());
                this.setProperty(propertyName, mappings);
            }
            catch (Throwable th)
            {
                String errMsg = "Error getting '" + propertyName + "' --> '" + uri + '\'';
                logger.error(errMsg, th);
                // don't throw the exception
            }
        }
        else
        {
            mappings = (TypeMappings)property;
        }
        return mappings;
    }

    /**
     * @see org.andromda.cartridges.webservice.metafacades.WSDLTypeLogic#handleGetNamespacePrefix()
     */
    protected String handleGetNamespacePrefix()
    {
        return (String)this.getConfiguredProperty(WebServiceFacadeLogicImpl.NAMESPACE_PREFIX);
    }

    /**
     * Gets the <code>qualifiedNameLocalPartPattern</code> for this WSDL type.
     * @return String getConfiguredProperty(WebServiceFacadeLogicImpl.QNAME_LOCAL_PART_PATTERN)
     */
    protected String getQualfiedNameLocalPartPattern()
    {
        return (String)this.getConfiguredProperty(WebServiceFacadeLogicImpl.QNAME_LOCAL_PART_PATTERN);
    }

    /**
     * Gets the <code>namespacePattern</code> for this type.
     * @return getConfiguredProperty(WebServiceFacadeLogicImpl.NAMESPACE_PATTERN)
     */
    protected String getNamespacePattern()
    {
        return (String)this.getConfiguredProperty(WebServiceFacadeLogicImpl.NAMESPACE_PATTERN);
    }

    /**
     * Gets whether or not <code>reverseNamespace</code> is true/false for this type.
     *
     * @return boolean true/false
     */
    private boolean isReverseNamespace()
    {
        return Boolean.valueOf(String.valueOf(this.getConfiguredProperty(WebServiceFacadeLogicImpl.REVERSE_NAMESPACE)))
                .booleanValue();
    }

    /**
     * @see org.andromda.cartridges.webservice.metafacades.WSDLTypeLogic#handleIsWebFaultAnException()
     */
    @Override
    protected boolean handleIsWebFaultAnException()
    {
        boolean result = true;
        if (this.hasStereotype(UMLProfile.STEREOTYPE_WEB_FAULT))
        {
            if (!this.hasStereotype(UMLProfile.STEREOTYPE_APPLICATION_EXCEPTION) &&
                !this.hasStereotype(UMLProfile.STEREOTYPE_UNEXPECTED_EXCEPTION) &&
                !this.hasStereotype(UMLProfile.STEREOTYPE_EXCEPTION))
            {
                result = false;
            }
        }
        return result;
    }

    private static final List<WebServiceOperationFacade> weboperations = new ArrayList<WebServiceOperationFacade>();
    /**
     * @see org.andromda.cartridges.webservice.metafacades.WSDLTypeLogic#handleIsWebFaultThrown()
     */
    @Override
    protected boolean handleIsWebFaultThrown()
    {
        boolean result = true;
        if (this.hasStereotype(UMLProfile.STEREOTYPE_WEB_FAULT))
        {
            result = false;
            // collect all webservice operations for the entire model in a static list, only once for all wsdl types
            if (weboperations.isEmpty())
            {
                for (ClassifierFacade classifier : this.getModel().getAllClasses())
                {
                    boolean isService = classifier.hasStereotype(UMLProfile.STEREOTYPE_WEBSERVICE);
                    for (OperationFacade operation : classifier.getOperations())
                    {
                        boolean visibility = operation.getVisibility().equals("public") || operation.getVisibility().equals("protected");
                        if (visibility && (isService || operation.hasStereotype(UMLProfile.STEREOTYPE_WEBSERVICE)))
                        {
                            weboperations.add((WebServiceOperationFacade)operation);
                        }
                    }
                }
            }
            for (WebServiceOperationFacade op : weboperations)
            {
                for (Object exception : op.getExceptions())
                {
                    if (((ModelElementFacade)exception).getFullyQualifiedName().equals(this.getFullyQualifiedName()))
                    {
                        // WebFault is actually thrown by a service - OK
                        result = true;
                        break;
                    }
                }
            }
        }
        return result;
    }

    @Override
    protected Object handleGetWebServiceFacade() {
        // TODO Auto-generated method stub
        return null;
    }
}