// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

/**
 * Represents a back-end service that can be accessed by a JSF controller.
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularBackendService.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularBackendService
 */
public class AngularBackendServiceLogicImpl
    extends AngularBackendServiceLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularBackendServiceLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularBackendService
     */
    public AngularBackendServiceLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * The implementation to use in a controller in order to get an instance of a back end service.
     * @see org.andromda.cartridges.angular.metafacades.AngularBackendService#getAccessorImplementation()
     */
    protected String handleGetAccessorImplementation()
    {
        // TODO put your implementation here.
        return null;
    }
}