// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

/**
 * Represents a criteria search model element.
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularCriteriaSearch.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularCriteriaSearch
 */
public class AngularCriteriaSearchLogicImpl
    extends AngularCriteriaSearchLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularCriteriaSearchLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularCriteriaSearch
     */
    public AngularCriteriaSearchLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }
}