// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Objects;

import org.andromda.cartridges.angular.AngularGlobals;
import org.andromda.cartridges.angular.AngularHelper;
import org.andromda.cartridges.angular.AngularProfile;
import org.andromda.cartridges.jsf2.JSFProfile;
import org.andromda.metafacades.uml.EventFacade;
import org.andromda.metafacades.uml.FrontEndControllerOperation;
import org.andromda.metafacades.uml.FrontEndForward;
import org.andromda.metafacades.uml.FrontEndParameter;
import org.andromda.metafacades.uml.FrontEndAction;
import org.andromda.metafacades.uml.FrontEndActionState;
import org.andromda.metafacades.uml.ModelElementFacade;
import org.andromda.utils.StringUtilsHelper;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;

/**
 * Represents an action taken during a "front-end" event execution on a JSF application.
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularAction.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularAction
 */
public class AngularActionLogicImpl
    extends AngularActionLogic
{
    private static final long serialVersionUID = 34L;
    private static final Logger LOGGER = Logger.getLogger(AngularActionLogicImpl.class);
    /**
     * Public constructor for AngularActionLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularAction
     */
    public AngularActionLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * The name of the form implementation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationName()
     */
    protected String handleGetFormImplementationName()
    {
        final String pattern =
        Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_IMPLEMENTATION_PATTERN));
        return pattern.replaceFirst(
            "\\{0\\}",
            StringUtils.capitalize(this.getTriggerName()));
    }

    /**
     * The name of the bean under which the form is stored.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormBeanName()
     */
    protected String handleGetFormBeanName()
    {
        
        return this.getFormBeanName(true);
    }

    /**
     * Constructs the form bean name, with our without prefixing the use case name.
     *
     * @param withUseCaseName whether or not to prefix the use case name.
     * @return the constructed form bean name.
     */
    private String getFormBeanName(boolean withUseCaseName)
    {
        final String pattern = Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_BEAN_PATTERN));
        final ModelElementFacade useCase = this.getUseCase();
        final String useCaseName = withUseCaseName && useCase != null
            ? StringUtilsHelper.lowerCamelCaseName(useCase.getName()) : "";
        final String formBeanName = pattern.replaceFirst("\\{0\\}", useCaseName);
        final String triggerName = !pattern.equals(formBeanName)
            ? StringUtils.capitalize(this.getTriggerName()) : this.getTriggerName();
        return formBeanName.replaceFirst(
            "\\{1\\}",
            triggerName);
    }

    /**
     * The fully qualified name of the form implementation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedFormImplementationName()
     */
    protected String handleGetFullyQualifiedFormImplementationName()
    {
        final StringBuilder fullyQualifiedName = new StringBuilder();
        final String packageName = this.getPackageName();
        if (StringUtils.isNotBlank(packageName))
        {
            fullyQualifiedName.append(packageName + '.');
        }
        return fullyQualifiedName.append(this.getFormImplementationName()).toString();
    }

    /**
     * The fully qualified path of the form implementation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedFormImplementationPath()
     */
    protected String handleGetFullyQualifiedFormImplementationPath()
    {
        return this.getFullyQualifiedFormImplementationName().replace(
            '.',
            '/');
    }

    /**
     * The scope of the JSF form (request, session,application,etc).
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormScope()
     */
    protected String handleGetFormScope()
    {
        String scope = Objects.toString(this.findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_FORM_SCOPE));
        if (StringUtils.isEmpty(scope))
        {
            scope = Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_SCOPE));
        }
        return scope;
    }

    /**
     * A comma separated list of all the form interfaces which the form implementation implements.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationInterfaceList()
     */
    protected String handleGetFormImplementationInterfaceList()
    {
        final List<FrontEndControllerOperation> deferredOperations = this.getDeferredOperations();
        for (final Iterator<FrontEndControllerOperation> iterator = deferredOperations.iterator(); iterator.hasNext();)
        {
            // - remove any forms that don't have arguments
            final AngularControllerOperation operation = (AngularControllerOperation)iterator.next();
            if (operation.getArguments().isEmpty())
            {
                iterator.remove();
            }
        }
        final StringBuilder list = new StringBuilder();
        for (final Iterator<FrontEndControllerOperation> iterator = deferredOperations.iterator(); iterator.hasNext();)
        {
            final AngularControllerOperation operation = (AngularControllerOperation)iterator.next();
            list.append(operation.getFormName());
            if (iterator.hasNext())
            {
                list.append(", ");
            }
        }
        return list.toString();
    }

    /**
     * The path to this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getPath()
     */
    protected String handleGetPath()
    {
        String path = this.getPathRoot() + '/' + this.getFileName();
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            if (useCase != null && useCase.isViewHasNameOfUseCase())
            {
                // - add the uc prefix to make the trigger name unique
                //   when a view contained within the use case has the same name
                //   as the use case
                path = path + "uc";
            }
        }
        return path;
    }

    /**
     * The path's root.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getPathRoot()
     */
    protected String handleGetPathRoot()
    {
        final StringBuilder pathRoot = new StringBuilder();
        final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
        if (useCase != null)
        {
            pathRoot.append(useCase.getPathRoot());
        }
        return pathRoot.toString();
    }

    /**
     * The default resource message key for this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getMessageKey()
     */
    protected String handleGetMessageKey()
    {
        String messageKey = null;

        final Object trigger = this.getTrigger();
        if (trigger instanceof AngularEvent)
        {
            final AngularEvent actionTrigger = (AngularEvent)trigger;
            messageKey = actionTrigger.getMessageKey();
        }
        return messageKey;
    }

    /**
     * A resource message key suited for the action''s documentation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getDocumentationKey()
     */
    protected String handleGetDocumentationKey()
    {
        final Object trigger = this.getTrigger();
        AngularEvent event = null;
        if (trigger instanceof AngularEvent)
        {
            event = (AngularEvent)trigger;
        }
        return (event == null ? this.getMessageKey() + ".is.an.action.without.trigger" : event.getMessageKey()) +
            '.' + AngularGlobals.DOCUMENTATION_MESSAGE_KEY_SUFFIX;
    }

    /**
     * The resource messsage value suited for the action''s documentation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getDocumentationValue()
     */
    protected String handleGetDocumentationValue()
    {
        final String value = StringUtilsHelper.toResourceMessage(getDocumentation(
                    "",
                    64,
                    false));
        return value == null ? "" : value;
    }

    /**
     * The name of the trigger that triggers that action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTriggerName()
     */
    protected String handleGetTriggerName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The path to the view fragment corresponding to this action
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getViewFragmentPath()
     */
    protected String handleGetViewFragmentPath()
    {
        String name = null;
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            if (useCase != null)
            {
                name = useCase.getName();
            }
        }
        else
        {
            final EventFacade trigger = this.getTrigger();
            final String suffix = trigger == null ? this.getTarget().getName() : trigger.getName();
            name = this.getSource().getName() + ' ' + suffix;
        }
        return StringUtilsHelper.lowerCamelCaseName(name);
    }

    /**
     * The name of the table link specified for this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTableLinkName()
     */
    protected String handleGetTableLinkName()
    {
        String tableLink = null;

        final Object value = findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_TABLELINK);
        if (value != null)
        {
            tableLink = StringUtils.trimToNull(value.toString());

            if (tableLink != null)
            {
                final int columnOffset = tableLink.indexOf('.');
                tableLink = columnOffset == -1 ? tableLink : tableLink.substring(
                        0,
                        columnOffset);
            }
        }

        return tableLink;
    }

    /**
     * The name of the column targetted by this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTableLinkColumnName()
     */
    protected String handleGetTableLinkColumnName()
    {
        String tableLink = null;
        final Object value = findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_TABLELINK);
        if (value != null)
        {
            tableLink = StringUtils.trimToNull(value.toString());

            if (tableLink != null)
            {
                final int columnOffset = tableLink.indexOf('.');
                tableLink = (columnOffset == -1 || columnOffset == tableLink.length() - 1)
                    ? null : tableLink.substring(columnOffset + 1);
            }
        }
        return tableLink;
    }

    /**
     * Indicates if a table link name has been specified and it properly targets a table
     * page-variable from the input page.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isTableLink()
     */
    protected boolean handleIsTableLink()
    {
        return this.getTableLinkParameter() != null;
    }

    /**
     * Indicates whether or not this action is represented by clicking on a hyperlink.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isHyperlink()
     */
    protected boolean handleIsHyperlink()
    {
        final Object value = findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_TYPE);
        return AngularGlobals.ACTION_TYPE_HYPERLINK.equalsIgnoreCase(value == null ? null : value.toString());
    }

    /**
     * The name of the action class that executes this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getActionClassName()
     */
    protected String handleGetActionClassName()
    {
        return StringUtilsHelper.upperCamelCaseName(this.getTriggerName());
    }

    /**
     * The fully qualified path to the action class that execute this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedActionClassPath()
     */
    protected String handleGetFullyQualifiedActionClassPath()
    {
        return this.getFullyQualifiedActionClassName().replace(
            '.',
            '/') + ".ts";
    }

    /**
     * The name of the action on the controller that executions this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getControllerAction()
     */
    protected String handleGetControllerAction()
    {
        return this.getTriggerName();
    }

    /**
     * The fully qualified name of the action class that execute this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedActionClassName()
     */
    protected String handleGetFullyQualifiedActionClassName()
    {
        final StringBuilder path = new StringBuilder();
        final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
        if (useCase != null)
        {
            final String packageName = useCase.getPackageName();
            if (StringUtils.isNotBlank(packageName))
            {
                path.append(packageName);
                path.append('.');
            }
        }
        path.append(this.getActionClassName());
        return path.toString();
    }

    /**
     * Indicates whether or not the values passed along with this action can be reset or not.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isResettable()
     */
    protected boolean handleIsResettable()
    {
        final Object value = findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_RESETTABLE);
        return this.isTrue(value == null ? null : value.toString());
    }

    /**
     * Convenient method to detect whether or not a String instance represents a boolean <code>true</code> value.
     */
    private boolean isTrue(String string)
    {
        return "yes".equalsIgnoreCase(string) || "true".equalsIgnoreCase(string) || "on".equalsIgnoreCase(string) ||
        "1".equalsIgnoreCase(string);
    }

    /**
     * The key that stores the form in which information is passed from one action to another.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormKey()
     */
    protected String handleGetFormKey()
    {
        final Object formKeyValue = this.findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_FORM_KEY);
        return formKeyValue == null ? Objects.toString(this.getConfiguredProperty(AngularGlobals.ACTION_FORM_KEY))
                                    : String.valueOf(formKeyValue);
    }

    /**
     * Indicates that this action works on all rows of the table from the table link relation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isTableAction()
     */
    protected boolean handleIsTableAction()
    {
        return AngularGlobals.ACTION_TYPE_TABLE.equals(this.findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_TYPE));
    }

    /**
     * Indicates whether or not at least one parameter on this action requires validation.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isValidationRequired()
     */
    protected boolean handleIsValidationRequired()
    {
        boolean required = false;
        for (final FrontEndParameter frontEndParam : this.getParameters())
        {
            if (frontEndParam instanceof AngularParameter)
            {
                final AngularParameter parameter = (AngularParameter)frontEndParam;
                if (parameter.isValidationRequired())
                {
                    required = true;
                    break;
                }
            }
        }
        return required;
    }

    /**
     * Indicates if this action forwards to a popup (this is determed when the targetted view is a
     * popup).
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isPopup()
     */
    protected boolean handleIsPopup()
    {
        boolean popup = Objects.toString(this.findTaggedValue(JSFProfile.TAGGEDVALUE_ACTION_TYPE)).equalsIgnoreCase(
            AngularGlobals.ACTION_TYPE_POPUP);
        return popup;
    }

    /**
     * Indicates if at least one parameter on the form requires being reset.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFormResetRequired()
     */
    protected boolean handleIsFormResetRequired()
    {
        boolean resetRequired = this.isFormReset();
        if (!resetRequired)
        {
            for (final FrontEndParameter feParameter : this.getParameters())
            {
                if (feParameter instanceof AngularParameter)
                {
                    final AngularParameter parameter = (AngularParameter)feParameter;
                    resetRequired = parameter.isReset();
                    if (resetRequired)
                    {
                        break;
                    }
                }
            }
        }
        return resetRequired;
    }

    /**
     * Whether or not the entire form should be reset (all action parameters on the form).
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFormReset()
     */
    protected boolean handleIsFormReset()
    {
        return Boolean.valueOf(Objects.toString(this.findTaggedValue(
            JSFProfile.TAGGEDVALUE_ACTION_FORM_RESET))).booleanValue();
    }

    /**
     * The signature of the accessor method that returns the form implementation instance.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationGetter()
     */
    protected String handleGetFormImplementationGetter()
    {
        return "get" + StringUtils.capitalize(this.getFormBeanName(false)) + "()";
    }

    /**
     * The calcuated serial version UID for this action's form.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormSerialVersionUID()
     */
    protected String handleGetFormSerialVersionUID()
    {
        final StringBuilder buffer = new StringBuilder();

        buffer.append(this.getName());

        final ModelElementFacade input = (ModelElementFacade)this.getInput();
        buffer.append(input != null ? input.getName() : "");

        final ModelElementFacade guard = this.getGuard();
        buffer.append(guard != null ? guard.getName() : "");

        final ModelElementFacade effect = this.getEffect();
        buffer.append(effect != null ? effect.getName() : "");

        final ModelElementFacade decisionsTrigger = this.getDecisionTrigger();
        buffer.append(decisionsTrigger != null ? decisionsTrigger.getName() : "");

        buffer.append(StringUtils.trimToEmpty(this.getActionClassName()));

        for (final FrontEndParameter parameter : this.getParameters())
        {
            buffer.append(parameter.getName());
        }

        for (final FrontEndForward forward : this.getActionForwards())
        {
            buffer.append(forward.getName());
        }

        for (final FrontEndAction action : this.getActions())
        {
            buffer.append(action.getName());
        }

        for (final FrontEndActionState state : this.getActionStates())
        {
            buffer.append(state.getName());
        }
        final String signature = buffer.toString();

        String serialVersionUID = String.valueOf(0L);
        try
        {
            MessageDigest md = MessageDigest.getInstance("SHA");
            byte[] hashBytes = md.digest(signature.getBytes());

            long hash = 0;
            for (int ctr = Math.min(
                        hashBytes.length,
                        8) - 1; ctr >= 0; ctr--)
            {
                hash = (hash << 8) | (hashBytes[ctr] & 0xFF);
            }
            serialVersionUID = String.valueOf(hash);
        }
        catch (final NoSuchAlgorithmException exception)
        {
            final String message = "Error performing AngularAction.getFormSerialVersionUID";
            LOGGER.error(
                message,
                exception);
        }
        return serialVersionUID;
    }

    /**
     * Indicates whether or not a final state is the target of this action.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFinalStateTarget()
     */
    protected boolean handleIsFinalStateTarget()
    {
        return this.getTarget() instanceof AngularFinalState;
    }

    /**
     * The name that corresponds to the from-outcome in an navigational rule.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFromOutcome()
     */
    protected String handleGetFromOutcome()
    {
        return this.getName();
    }

    /**
     * Whether or not any warning messages are present.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isWarningMessagesPresent()
     */
    protected boolean handleIsWarningMessagesPresent()
    {
        return !this.getWarningMessages().isEmpty();
    }

    /**
     * Any messages used to indicate a warning.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getWarningMessages()
     */
    protected Map handleGetWarningMessages()
    {
        return this.getMessages(JSFProfile.TAGGEDVALUE_ACTION_WARNING_MESSAGE);
    }

    /**
     * Indicates whether or not any success messags are present.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isSuccessMessagesPresent()
     */
    protected boolean handleIsSuccessMessagesPresent()
    {
        return !this.getSuccessMessages().isEmpty();
    }

    /**
     * Messages used to indicate successful execution.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getSuccessMessages()
     */
    protected Map<String, String> handleGetSuccessMessages()
    {
        return this.getMessages(JSFProfile.TAGGEDVALUE_ACTION_SUCCESS_MESSAGE);
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularAction.needsFileUpload
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isNeedsFileUpload()
     */
    protected boolean handleIsNeedsFileUpload()
    {
        if(this.getParameters().size() == 0)
        {
            return false;
        }

        for (final FrontEndParameter feParameter : this.getParameters())
        {
            if (feParameter instanceof AngularParameter)
            {
                final AngularParameter parameter = (AngularParameter)feParameter;
                if(parameter.isInputFile())
                {
                    return true;
                }
                if(parameter.isComplex())
                {
                    for(final Iterator attributes = parameter.getAttributes().iterator(); attributes.hasNext();)
                        if(((AngularAttribute)attributes.next()).isInputFile())
                            return true;
                }
            }
        }
        return false;
    }

    /**
     * The name of the method to be executed when this action is triggered.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTriggerMethodName()
     */
    protected String handleGetTriggerMethodName()
    {
        final StringBuilder methodName = new StringBuilder();
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            methodName.append(StringUtilsHelper.lowerCamelCaseName(useCase.getName())+"_started");
        }
        else
        {
            methodName.append(StringUtilsHelper.lowerCamelCaseName(this.getSource().getName()));
            methodName.append('_');
            final EventFacade trigger = this.getTrigger();
            final String suffix = trigger == null ? this.getTarget().getName() : trigger.getName();
            methodName.append(StringUtilsHelper.lowerCamelCaseName(suffix));
        }
        return "_"+methodName.toString();
    }
    
    /**
     * Collects specific messages in a map.
     *
     * @param taggedValue the tagged value from which to read the message
     * @return maps message keys to message values, but only those that match the arguments
     *         will have been recorded
     */
    private Map<String, String> getMessages(String taggedValue)
    {
        Map<String, String> messages;

        final Collection taggedValues = this.findTaggedValues(taggedValue);
        if (taggedValues.isEmpty())
        {
            messages = Collections.EMPTY_MAP;
        }
        else
        {
            messages = new LinkedHashMap<String, String>(); // we want to keep the order
            for (final Object tag : taggedValues)
            {
                final String value = (String)tag;
                messages.put(StringUtilsHelper.toResourceMessageKey(value), value);
            }
        }

        return messages;
    }

    /**
     * Represents an action taken during a "front-end" event execution on a JSF application.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTableLinkParameter()
     */
    protected Object handleGetTableLinkParameter()
    {
        AngularParameter tableLinkParameter = null;
        final String tableLinkName = this.getTableLinkName();
        if (tableLinkName != null)
        {
            final AngularView view = (AngularView)this.getInput();
            if (view != null)
            {
                final List<FrontEndParameter> tables = view.getTables();
                for (int ctr = 0; ctr < tables.size() && tableLinkParameter == null; ctr++)
                {
                    final Object object = tables.get(ctr);
                    if (object instanceof AngularParameter)
                    {
                        final AngularParameter table = (AngularParameter)object;
                        if (tableLinkName.equals(table.getName()))
                        {
                            tableLinkParameter = table;
                        }
                    }
                }
            }
        }
        return tableLinkParameter;
    }

    /**
     * Represents an action taken during a "front-end" event execution on a JSF application.
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getHiddenParameters()
     */
    protected List<FrontEndParameter> handleGetHiddenParameters()
    {
        final List<FrontEndParameter> hiddenParameters = new ArrayList<FrontEndParameter>(this.getParameters());
        CollectionUtils.filter(
            hiddenParameters,
            new Predicate()
            {
                public boolean evaluate(final Object object)
                {
                    boolean valid = false;
                    if (object instanceof AngularParameter)
                    {
                        final AngularParameter parameter = (AngularParameter)object;
                        valid = parameter.isInputHidden();
                        if (!valid)
                        {
                            for (final Iterator iterator = parameter.getAttributes().iterator(); iterator.hasNext();)
                            {
                                AngularAttribute attribute = (AngularAttribute)iterator.next();
                                valid = attribute.isInputHidden();
                                if (valid)
                                {
                                    break;
                                }
                            }
                        }
                    }
                    return valid;
                }
            });
        return hiddenParameters;
    }

    @Override
    protected String handleGetFileName() {
        
        return AngularHelper.getComponentFileName(this.getName());
    }
}