// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;

import org.andromda.cartridges.angular.AngularGlobals;
import org.andromda.cartridges.angular.AngularProfile;
import org.andromda.cartridges.angular.AngularUtils;
import org.andromda.metafacades.uml.EventFacade;
import org.andromda.metafacades.uml.FrontEndAction;
import org.andromda.metafacades.uml.FrontEndActionState;
import org.andromda.metafacades.uml.FrontEndControllerOperation;
import org.andromda.metafacades.uml.FrontEndForward;
import org.andromda.metafacades.uml.FrontEndParameter;
import org.andromda.metafacades.uml.FrontEndView;
import org.andromda.metafacades.uml.ModelElementFacade;
import org.andromda.metafacades.uml.UseCaseFacade;
import org.andromda.utils.StringUtilsHelper;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;

/**
 * Represents an action taken during a "front-end" event execution on a Angular application.
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularAction.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularAction
 */
public class AngularActionLogicImpl
    extends AngularActionLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularActionLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularAction
     */
    public AngularActionLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * The logger instance.
     */
    private static final Logger LOGGER = Logger.getLogger(AngularActionLogicImpl.class);

    /**
     * @return getFormBeanName(true)
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormBeanName()
     */
    protected String handleGetFormBeanName()
    {
        return this.getFormBeanName(true);
    }

    /**
     * Constructs the form bean name, with our without prefixing the use case name.
     *
     * @param withUseCaseName whether or not to prefix the use case name.
     * @return the constructed form bean name.
     */
    private String getFormBeanName(boolean withUseCaseName)
    {
        final String pattern = Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_BEAN_PATTERN), "");
        final ModelElementFacade useCase = this.getUseCase();
        final String useCaseName = withUseCaseName && useCase != null
            ? StringUtilsHelper.lowerCamelCaseName(useCase.getName()) : "";
        final String formBeanName = pattern.replaceFirst("\\{0\\}", useCaseName);
        final String triggerName = !pattern.equals(formBeanName)
            ? StringUtils.capitalize(this.getTriggerName()) : this.getTriggerName();
        return formBeanName.replaceFirst(
            "\\{1\\}",
            triggerName);
    }

    /**
     * @see org.andromda.metafacades.uml.ModelElementFacade#getName()
     */
    public String getName()
    {
        return AngularUtils.toWebResourceName(this.getUseCase().getName() + "-" + super.getName());
    }

    /**
     * @return useCase.getName()
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTriggerName()
     */
    protected String handleGetTriggerName()
    {
        String name = null;
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            if (useCase != null)
            {
                name = useCase.getName();
            }
        }
        else
        {
            final EventFacade trigger = this.getTrigger();
            final String suffix = trigger == null ? this.getTarget().getName() : trigger.getName();
            name = this.getSource().getName() + ' ' + suffix;
        }
        return StringUtilsHelper.lowerCamelCaseName(name);
    }

    /**
     * @return formImplementationName
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationName()
     */
    protected String handleGetFormImplementationName()
    {
        final String pattern =
            Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_IMPLEMENTATION_PATTERN), "");
        return pattern.replaceFirst(
            "\\{0\\}",
            StringUtils.capitalize(this.getTriggerName()));
    }

    /**
     * @return isTableAction
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedFormImplementationName()
     */
    protected boolean handleIsTableAction()
    {
        return AngularGlobals.ACTION_TYPE_TABLE.equals(this.findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TYPE));
    }

    /**
     * @return scope
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedFormImplementationPath()
     */
    protected String handleGetFormScope()
    {
        String scope = Objects.toString(this.findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_FORM_SCOPE));
        if (StringUtils.isEmpty(scope))
        {
            scope = Objects.toString(this.getConfiguredProperty(AngularGlobals.FORM_SCOPE), "");
        }
        return scope;
    }

    /**
     * @return formImplementationInterfaceList
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationInterfaceList()
     */
    protected String handleGetFormImplementationInterfaceList()
    {
        final List<FrontEndControllerOperation> deferredOperations = this.getDeferredOperations();
        for (final Iterator<FrontEndControllerOperation> iterator = deferredOperations.iterator(); iterator.hasNext();)
        {
            // - remove any forms that don't have arguments
            final AngularControllerOperation operation = (AngularControllerOperation)iterator.next();
            if (operation.getArguments().isEmpty())
            {
                iterator.remove();
            }
        }
        final StringBuilder list = new StringBuilder();
        for (final Iterator<FrontEndControllerOperation> iterator = deferredOperations.iterator(); iterator.hasNext();)
        {
            final AngularControllerOperation operation = (AngularControllerOperation)iterator.next();
            list.append(operation.getFormName());
            if (iterator.hasNext())
            {
                list.append(", ");
            }
        }
        return list.toString();
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularActionLogic#handleGetPath()
     */
    protected String handleGetPath()
    {
        String path = this.getPathRoot() + '/' + AngularUtils.toWebResourceName(this.getTriggerName());
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            if (useCase != null && useCase.isViewHasNameOfUseCase())
            {
                // - add the uc prefix to make the trigger name unique
                //   when a view contained within the use case has the same name
                //   as the use case
                path = path + "uc";
            }
        }
        return path;
    }

    /**
     * @return pathRoot
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getPathRoot()
     */
    protected String handleGetPathRoot()
    {
        final StringBuilder pathRoot = new StringBuilder();
        final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
        if (useCase != null)
        {
            pathRoot.append(useCase.getPathRoot());
        }
        return pathRoot.toString();
    }

    /**
     * @return messageKey
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getMessageKey()
     */
    protected String handleGetMessageKey()
    {
        String messageKey = null;

        final Object trigger = this.getTrigger();
        if (trigger instanceof AngularEvent)
        {
            final AngularEvent actionTrigger = (AngularEvent)trigger;
            messageKey = actionTrigger.getMessageKey();
        }
        return messageKey;
    }

    /**
     * @return documentationKey
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getDocumentationKey()
     */
    protected String handleGetDocumentationKey()
    {
        final Object trigger = this.getTrigger();
        AngularEvent event = null;
        if (trigger instanceof AngularEvent)
        {
            event = (AngularEvent)trigger;
        }
        return (event == null ? this.getMessageKey() + ".is.an.action.without.trigger" : event.getMessageKey()) +
            '.' + AngularGlobals.DOCUMENTATION_MESSAGE_KEY_SUFFIX;
    }

    /**
     * @return documentationValue
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getDocumentationValue()
     */
    protected String handleGetDocumentationValue()
    {
        final String value = StringUtilsHelper.toResourceMessage(getDocumentation(
                    "",
                    64,
                    false));
        return value == null ? "" : value;
    }

    /**
     * @return viewFragmentPath
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getViewFragmentPath()
     */
    protected String handleGetViewFragmentPath()
    {
        return '/' + this.getPackageName().replace(
            '.',
            '/') + '/' + AngularUtils.toWebResourceName(this.getTriggerName());
    }

    /**
     * @return tableLink
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTableLinkName()
     */
    protected String handleGetTableLinkName()
    {
        String tableLink = null;

        final Object value = findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TABLELINK);
        if (value != null)
        {
            tableLink = StringUtils.trimToNull(value.toString());

            if (tableLink != null)
            {
                final int columnOffset = tableLink.indexOf('.');
                tableLink = columnOffset == -1 ? tableLink : tableLink.substring(
                        0,
                        columnOffset);
            }
        }

        return tableLink;
    }

    /**
     * @return tableLink
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTableLinkColumnName()
     */
    protected String handleGetTableLinkColumnName()
    {
        String tableLink = null;
        final Object value = findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TABLELINK);
        if (value != null)
        {
            tableLink = StringUtils.trimToNull(value.toString());

            if (tableLink != null)
            {
                final int columnOffset = tableLink.indexOf('.');
                tableLink = (columnOffset == -1 || columnOffset == tableLink.length() - 1)
                    ? null : tableLink.substring(columnOffset + 1);
            }
        }
        return tableLink;
    }

    /**
     * @return tableLinkParameter
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isTableLink()
     */
    protected Object handleGetTableLinkParameter()
    {
        AngularParameter tableLinkParameter = null;
        final String tableLinkName = this.getTableLinkName();
        if (tableLinkName != null)
        {
            final AngularView view = (AngularView)this.getInput();
            if (view != null)
            {
                final List<FrontEndParameter> tables = view.getTables();
                for (int ctr = 0; ctr < tables.size() && tableLinkParameter == null; ctr++)
                {
                    final Object object = tables.get(ctr);
                    if (object instanceof AngularParameter)
                    {
                        final AngularParameter table = (AngularParameter)object;
                        if (tableLinkName.equals(table.getName()))
                        {
                            tableLinkParameter = table;
                        }
                    }
                }
            }
        }
        return tableLinkParameter;
    }

    /**
     * @return getTableLinkParameter() != null
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isTableLink()
     */
    protected boolean handleIsTableLink()
    {
        return this.getTableLinkParameter() != null;
    }

    /**
     * @return hyperlink
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isHyperlink()
     */
    protected boolean handleIsHyperlink()
    {
        final Object value = findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TYPE);
        return AngularGlobals.ACTION_TYPE_HYPERLINK.equalsIgnoreCase(value == null ? null : value.toString());
    }

    /**
     * @return StringUtilsHelper.upperCamelCaseName(this.getTriggerName())
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getActionClassName()
     */
    protected String handleGetActionClassName()
    {
        return StringUtilsHelper.upperCamelCaseName(this.getTriggerName());
    }

    /**
     * @return fullyQualifiedActionClassPath
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedActionClassPath()
     */
    protected String handleGetFullyQualifiedActionClassPath()
    {
        return this.getFullyQualifiedActionClassName().replace(
            '.',
            '/') + ".java";
    }

    /**
     * Overridden to provide the owning use case's package name.
     *
     * @see org.andromda.metafacades.uml.ModelElementFacade#getPackageName()
     */
    public String getPackageName()
    {
        final UseCaseFacade useCase = this.getUseCase();
        return useCase != null ? useCase.getPackageName() : "";
    }

    /**
     * @return getTriggerName()
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getControllerAction()
     */
    protected String handleGetControllerAction()
    {
        return this.getTriggerName();
    }

    /**
     * @return fullyQualifiedActionClassName
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFullyQualifiedActionClassName()
     */
    protected String handleGetFullyQualifiedActionClassName()
    {
        final StringBuilder path = new StringBuilder();
        final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
        if (useCase != null)
        {
            final String packageName = useCase.getPackageName();
            if (StringUtils.isNotBlank(packageName))
            {
                path.append(packageName);
                path.append('.');
            }
        }
        path.append(this.getActionClassName());
        return path.toString();
    }

    /**
     * @return findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_RESETTABLE) isTrue
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isResettable()
     */
    protected boolean handleIsResettable()
    {
        final Object value = findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_RESETTABLE);
        return this.isTrue(value == null ? null : value.toString());
    }

    /**
     * Convenient method to detect whether or not a String instance represents a boolean <code>true</code> value.
     */
    private boolean isTrue(String string)
    {
        return "yes".equalsIgnoreCase(string) || "true".equalsIgnoreCase(string) || "on".equalsIgnoreCase(string) ||
        "1".equalsIgnoreCase(string);
    }

    /**
     * @return otherActions
     */
    protected List<FrontEndAction> handleGetOtherUseCaseFormActions()
    {
        final List<FrontEndAction> otherActions = new ArrayList<FrontEndAction>(this.getUseCase().getActions());
        for (final Iterator<FrontEndAction> iterator = otherActions.iterator(); iterator.hasNext();)
        {
            final FrontEndAction action = iterator.next();

            // - remove this action and any forms that don't have form fields
            if (action.equals(this.THIS()) || action.getFormFields().isEmpty())
            {
                iterator.remove();
            }
        }
        return otherActions;
    }

    /**
     * @return hiddenParameters
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormKey()
     */
    protected String handleGetFormKey()
    {
        final Object formKeyValue = this.findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_FORM_KEY);
        return formKeyValue == null ? Objects.toString(this.getConfiguredProperty(AngularGlobals.ACTION_FORM_KEY), "")
                                    : String.valueOf(formKeyValue);
    }

    /**
     * @return hiddenParameters
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getHiddenParameters()
     */
    protected List<FrontEndParameter> handleGetHiddenParameters()
    {
        final List<FrontEndParameter> hiddenParameters = new ArrayList<FrontEndParameter>(this.getParameters());
        CollectionUtils.filter(
            hiddenParameters,
            new Predicate()
            {
                public boolean evaluate(final Object object)
                {
                    boolean valid = false;
                    if (object instanceof AngularParameter)
                    {
                        final AngularParameter parameter = (AngularParameter)object;
                        valid = parameter.isInputHidden();
                        if (!valid)
                        {
                            for (final Iterator iterator = parameter.getAttributes().iterator(); iterator.hasNext();)
                            {
                                AngularAttribute attribute = (AngularAttribute)iterator.next();
                                valid = attribute.isInputHidden();
                                if (valid)
                                {
                                    break;
                                }
                            }
                        }
                    }
                    return valid;
                }
            });
        return hiddenParameters;
    }

    /**
     * @return required
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getHiddenParameters()
     */
    protected boolean handleIsValidationRequired()
    {
        boolean required = false;
        for (final FrontEndParameter frontEndParam : this.getParameters())
        {
            if (frontEndParam instanceof AngularParameter)
            {
                final AngularParameter parameter = (AngularParameter)frontEndParam;
                if (parameter.isValidationRequired())
                {
                    required = true;
                    break;
                }
            }
        }
        return required;
    }

    /**
     * @return popup
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isPopup()
     */
    protected boolean handleIsPopup()
    {
        boolean popup = Objects.toString(this.findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TYPE), "").equalsIgnoreCase(
            AngularGlobals.ACTION_TYPE_POPUP);
        return popup;
    }

    /**
     * @return dialog
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isDialog()
     */
    protected boolean handleIsDialog()
    {
        return this.isPopup();
        //currently only popup dialogs are supported and all dialog = popup.
        //It should change when Angular
        //starts supporting some conversation scope, or the Angular cartridge supports
        //some extension that adds this kind of feature
        
//        boolean dialog = ObjectUtils.toString(this.findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_TYPE)).equalsIgnoreCase(
//            AngularGlobals.ACTION_TYPE_DIALOG);
//        return dialog;
    }

    /**
     * @return resetRequired
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFormResetRequired()
     */
    protected boolean handleIsFormResetRequired()
    {
        boolean resetRequired = this.isFormReset();
        if (!resetRequired)
        {
            for (final FrontEndParameter feParameter : this.getParameters())
            {
                if (feParameter instanceof AngularParameter)
                {
                    final AngularParameter parameter = (AngularParameter)feParameter;
                    resetRequired = parameter.isReset();
                    if (resetRequired)
                    {
                        break;
                    }
                }
            }
        }
        return resetRequired;
    }

    //TODO remove after 3.4 release
    /**
     * Hack to keep the compatibility with Andromda 3.4-SNAPSHOT
     * @return getSource() instanceof FrontEndView
     */
    public FrontEndView getInput()
    {
        FrontEndView input = null;
        final ModelElementFacade source = this.getSource();
        if (source instanceof FrontEndView)
        {
            input = (FrontEndView)source;
        }
        return input;
    }

    /**
     * @return formSerialVersionUID
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormSerialVersionUID()
     */
    protected String handleGetFormSerialVersionUID()
    {
        final StringBuilder buffer = new StringBuilder();

        buffer.append(this.getName());

        final ModelElementFacade input = (ModelElementFacade)this.getInput();
        buffer.append(input != null ? input.getName() : "");

        final ModelElementFacade guard = this.getGuard();
        buffer.append(guard != null ? guard.getName() : "");

        final ModelElementFacade effect = this.getEffect();
        buffer.append(effect != null ? effect.getName() : "");

        final ModelElementFacade decisionsTrigger = this.getDecisionTrigger();
        buffer.append(decisionsTrigger != null ? decisionsTrigger.getName() : "");

        buffer.append(StringUtils.trimToEmpty(this.getActionClassName()));

        for (final FrontEndParameter parameter : this.getParameters())
        {
            buffer.append(parameter.getName());
        }

        for (final FrontEndForward forward : this.getActionForwards())
        {
            buffer.append(forward.getName());
        }

        for (final FrontEndAction action : this.getActions())
        {
            buffer.append(action.getName());
        }

        for (final FrontEndActionState state : this.getActionStates())
        {
            buffer.append(state.getName());
        }
        final String signature = buffer.toString();

        String serialVersionUID = String.valueOf(0L);
        try
        {
            MessageDigest md = MessageDigest.getInstance("SHA");
            byte[] hashBytes = md.digest(signature.getBytes());

            long hash = 0;
            for (int ctr = Math.min(
                        hashBytes.length,
                        8) - 1; ctr >= 0; ctr--)
            {
                hash = (hash << 8) | (hashBytes[ctr] & 0xFF);
            }
            serialVersionUID = String.valueOf(hash);
        }
        catch (final NoSuchAlgorithmException exception)
        {
            final String message = "Error performing AngularAction.getFormSerialVersionUID";
            LOGGER.error(
                message,
                exception);
        }
        return serialVersionUID;
    }

    /**
     * @return findTaggedValue(AngularProfile.TAGGEDVALUE_ACTION_FORM_RESET)
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFormResetRequired()
     */
    protected boolean handleIsFormReset()
    {
        return Boolean.valueOf(Objects.toString(this.findTaggedValue(
            AngularProfile.TAGGEDVALUE_ACTION_FORM_RESET), "")).booleanValue();
    }

    /**
     * @return "get" + StringUtils.capitalize(this.getFormBeanName(false)) + "()"
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFormImplementationGetter()
     */
    protected String handleGetFormImplementationGetter()
    {
        return "get" + StringUtils.capitalize(this.getFormBeanName(false)) + "()";
    }

    /**
     * @return getTarget() instanceof AngularFinalState
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isFinalStateTarget()
     */
    protected boolean handleIsFinalStateTarget()
    {
        return this.getTarget() instanceof AngularFinalState;
    }

    /**
     * @return getName()
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getFromOutcome()
     */
    protected String handleGetFromOutcome()
    {
        return this.getName();
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularActionLogic#handleIsSuccessMessagesPresent()
     */
    protected boolean handleIsSuccessMessagesPresent()
    {
        return !this.getSuccessMessages().isEmpty();
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularActionLogic#handleIsWarningMessagesPresent()
     */
    protected boolean handleIsWarningMessagesPresent()
    {
        return !this.getWarningMessages().isEmpty();
    }

    /**
     * Collects specific messages in a map.
     *
     * @param taggedValue the tagged value from which to read the message
     * @return maps message keys to message values, but only those that match the arguments
     *         will have been recorded
     */
    private Map<String, String> getMessages(String taggedValue)
    {
        Map<String, String> messages;

        final Collection taggedValues = this.findTaggedValues(taggedValue);
        if (taggedValues.isEmpty())
        {
            messages = Collections.EMPTY_MAP;
        }
        else
        {
            messages = new LinkedHashMap<String, String>(); // we want to keep the order
            for (final Object tag : taggedValues)
            {
                final String value = (String)tag;
                messages.put(StringUtilsHelper.toResourceMessageKey(value), value);
            }
        }

        return messages;
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularActionLogic#handleGetSuccessMessages()
     */
    protected Map<String, String> handleGetSuccessMessages()
    {
        return this.getMessages(AngularProfile.TAGGEDVALUE_ACTION_SUCCESS_MESSAGE);
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularActionLogic#handleGetWarningMessages()
     */
    protected Map<String, String> handleGetWarningMessages()
    {
        return this.getMessages(AngularProfile.TAGGEDVALUE_ACTION_WARNING_MESSAGE);
    }

    /**
     * @return needsFileUpload
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#isNeedsFileUpload()
     */
    protected boolean handleIsNeedsFileUpload()
    {
        if(this.getParameters().size() == 0)
        {
            return false;
        }

        for (final FrontEndParameter feParameter : this.getParameters())
        {
            if (feParameter instanceof AngularParameter)
            {
                final AngularParameter parameter = (AngularParameter)feParameter;
                if(parameter.isInputFile())
                {
                    return true;
                }
                if(parameter.isComplex())
                {
                    for(final Iterator attributes = parameter.getAttributes().iterator(); attributes.hasNext();)
                        if(((AngularAttribute)attributes.next()).isInputFile())
                            return true;
                }
            }
        }
        return false;
    }

    /**
     * @see org.andromda.cartridges.angular.metafacades.AngularAction#getTriggerMethodName
     */
    @Override
    protected String handleGetTriggerMethodName()
    {
        final StringBuilder methodName = new StringBuilder();
        if (this.isExitingInitialState())
        {
            final AngularUseCase useCase = (AngularUseCase)this.getUseCase();
            methodName.append(StringUtilsHelper.lowerCamelCaseName(useCase.getName())+"_started");
        }
        else
        {
            methodName.append(StringUtilsHelper.lowerCamelCaseName(this.getSource().getName()));
            methodName.append('_');
            final EventFacade trigger = this.getTrigger();
            final String suffix = trigger == null ? this.getTarget().getName() : trigger.getName();
            methodName.append(StringUtilsHelper.lowerCamelCaseName(suffix));
        }
        return "_"+methodName.toString();
    }

    @Override
    protected Collection<ModelElementFacade> handleGetImports() {
        HashSet<ModelElementFacade> imports = new HashSet<>();
        
        for(FrontEndParameter _parameter : this.getParameters()) {
            AngularParameter parameter = (AngularParameter) _parameter;
            
            if(parameter.isComplex()) {
                imports.add(parameter.getType());

                for (Object _attribute : parameter.getAttributes()) {
                    AngularAttribute attribute = (AngularAttribute) _attribute;
                    if (attribute.getType().getAttributes() != null
                            && !attribute.getType().getAttributes().isEmpty()) {
                        imports.add(attribute.getType());
                    }
                }
            }
        }

        for (FrontEndParameter _field : this.getFormFields()) {
            AngularParameter field = (AngularParameter) _field;

            if (field.isComplex()) {
                imports.add(field.getType());
            }
        }

        if(this.getController() != null) {
            imports.addAll(((AngularController)this.getController()).getAllRestControllers());
            imports.add(this.getController());
        }

        return imports;
    }

    @Override
    protected String handleGetFileName() {
        
        String phrase = StringUtilsHelper.toPhrase(this.getName()).toLowerCase();
        return phrase.replace(" ", "-") + ".component";
    }

    @Override
    protected String handleGetFilePath() {
        return "view/" + this.getPackagePath() + "/" + this.getFileName();
    }

    @Override
    protected String handleGetImplementationFileName() {
        return this.getFileName() + ".impl";
    }

    @Override
    protected String handleGetImplementationFilePath() {
        return this.getFilePath() + ".impl";
    }

    @Override
    protected String handleGetSelectorName() {
        String phrase = StringUtilsHelper.toPhrase(this.getName()).toLowerCase();
        return phrase.replace(" ", "-");
    }

    @Override
    protected String handleGetRouterPath() {
        return this.getSelectorName().replace("-", "");
    }

    @Override
    protected String handleGetComponentImplementationName() {
        
        return this.getActionClassName() + "ComponentImpl";
    }

    @Override
    protected String handleGetFormEventName() {
        return StringUtilsHelper.uncapitalize(this.getActionClassName()) + "Event";
    }

    @Override
    protected String handleGetFormName() {
        return StringUtilsHelper.uncapitalize(this.getActionClassName()) + "Form";
    }

    @Override
    protected String handleGetComponentName() {
        return this.getActionClassName() + "Component";
    }

    @Override
    protected String handleGetVariableName() {
        return StringUtilsHelper.uncapitalize(this.getComponentName());
    }

}