// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

import java.util.Collection;
import org.andromda.metafacades.uml.ParameterFacade;

/**
 * TODO: Model Documentation for
 * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute
 */
public class AngularManageableEntityAttributeLogicImpl
    extends AngularManageableEntityAttributeLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularManageableEntityAttributeLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute
     */
    public AngularManageableEntityAttributeLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.messageKey
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getMessageKey()
     */
    protected String handleGetMessageKey()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.messageValue
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getMessageValue()
     */
    protected String handleGetMessageValue()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The String format to use when referring to this date, only makes sense when the type is a
     * date type.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getDateFormat()
     */
    protected String handleGetDateFormat()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * True if this attribute is of a type that cannot easily be represented as a textual string and
     * would be an ideal candidate for HTTP's support for file-upload.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isNeedsFileUpload()
     */
    protected boolean handleIsNeedsFileUpload()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * Whether or not this attribute should be hidden from the view
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isHidden()
     */
    protected boolean handleIsHidden()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * The widget to use when rendering this attribute
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getWidgetType()
     */
    protected String handleGetWidgetType()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * True if this field is a date type and the date format is not be interpreted strictly.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isStrictDateFormat()
     */
    protected boolean handleIsStrictDateFormat()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * The key to lookup the online help documentation. This documentation is gathered from the
     * documentation entered by the user, as well as analyzing the model.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getOnlineHelpKey()
     */
    protected String handleGetOnlineHelpKey()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The online help documentation. This documentation is gathered from the documentation entered
     * by the user, as well as analyzing the model. The format is HTML without any style.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getOnlineHelpValue()
     */
    protected String handleGetOnlineHelpValue()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.format
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getFormat()
     */
    protected String handleGetFormat()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.defaultDateFormat
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getDefaultDateFormat()
     */
    protected String handleGetDefaultDateFormat()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.defaultTimeFormat
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getDefaultTimeFormat()
     */
    protected String handleGetDefaultTimeFormat()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.dateFormatter
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getDateFormatter()
     */
    protected String handleGetDateFormatter()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.timeFormatter
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getTimeFormatter()
     */
    protected String handleGetTimeFormatter()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.backingListName
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getBackingListName()
     */
    protected String handleGetBackingListName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.valueListName
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValueListName()
     */
    protected String handleGetValueListName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.labelListName
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getLabelListName()
     */
    protected String handleGetLabelListName()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * All validator types for this attribute.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValidatorTypes()
     */
    protected Collection handleGetValidatorTypes()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Indicates whether or not this attribute requires some kind of validation (the collection of
     * validator types is not empty).
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isValidationRequired()
     */
    protected boolean handleIsValidationRequired()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.validWhen
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValidWhen()
     */
    protected String handleGetValidWhen()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputCheckbox
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputCheckbox()
     */
    protected boolean handleIsInputCheckbox()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputFile
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputFile()
     */
    protected boolean handleIsInputFile()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputHidden
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputHidden()
     */
    protected boolean handleIsInputHidden()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputMultibox
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputMultibox()
     */
    protected boolean handleIsInputMultibox()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputRadio
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputRadio()
     */
    protected boolean handleIsInputRadio()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputSecret
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputSecret()
     */
    protected boolean handleIsInputSecret()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputSelect
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputSelect()
     */
    protected boolean handleIsInputSelect()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputTable
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputTable()
     */
    protected boolean handleIsInputTable()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputTableIdentifierColumns
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getInputTableIdentifierColumns()
     */
    protected String handleGetInputTableIdentifierColumns()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputText
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputText()
     */
    protected boolean handleIsInputText()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputTextarea
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputTextarea()
     */
    protected boolean handleIsInputTextarea()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.inputTypePresent
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isInputTypePresent()
     */
    protected boolean handleIsInputTypePresent()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.dummyValue
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getDummyValue()
     */
    protected String handleGetDummyValue()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.equalValidator
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isEqualValidator()
     */
    protected boolean handleIsEqualValidator()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.plaintext
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#isPlaintext()
     */
    protected boolean handleIsPlaintext()
    {
        // TODO put your implementation here.
        return false;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.valueListDummyValue
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValueListDummyValue()
     */
    protected String handleGetValueListDummyValue()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The validator variables.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValidatorVars()
     */
    protected Collection handleGetValidatorVars()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * The max length allowed in the input component
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getMaxLength()
     */
    protected String handleGetMaxLength()
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * TODO: Model Documentation for
     * org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute.getValidatorArgs
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getValidatorArgs(String)
     */
    protected Collection handleGetValidatorArgs(String validatorType)
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Gets the unique id of this attribute on the form.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getFormPropertyId(ParameterFacade)
     */
    protected String handleGetFormPropertyId(ParameterFacade ownerParameter)
    {
        // TODO put your implementation here.
        return null;
    }

    /**
     * Retrieves the name of the form property for this attribute by taking the name of the owner
     * property.
     * @see org.andromda.cartridges.angular.metafacades.AngularManageableEntityAttribute#getFormPropertyName(ParameterFacade)
     */
    protected String handleGetFormPropertyName(ParameterFacade ownerParameter)
    {
        // TODO put your implementation here.
        return null;
    }
}