// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.angular.metafacades;

/**
 * Represents the portlet preferences for a given use case (assuming the JSF application being
 * generated is a portlet).
 * MetafacadeLogic implementation for org.andromda.cartridges.angular.metafacades.AngularPortletPreferences.
 *
 * @see org.andromda.cartridges.angular.metafacades.AngularPortletPreferences
 */
public class AngularPortletPreferencesLogicImpl
    extends AngularPortletPreferencesLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for AngularPortletPreferencesLogicImpl
     * @see org.andromda.cartridges.angular.metafacades.AngularPortletPreferences
     */
    public AngularPortletPreferencesLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }

    /**
     * Any portlet preferences associated to this use case.
     * @see org.andromda.cartridges.angular.metafacades.AngularPortletPreferences#getUseCase()
     */
    protected Object handleGetUseCase()
    {
        // TODO add your implementation here!
        return null;
    }
}